openapi: 3.0.3
info:
  title: HomeManager AI Gateway API
  description: |
    AI-powered insights and recommendations service for HomeManager system.
    Integrates with Amazon Bedrock and MCP servers for intelligent features.
  version: 1.0.0
  contact:
    name: HomeManager Development Team
    url: https://github.com/kjaworski/HomeManager
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://api.homemanager.local/ai
    description: Local development server
  - url: https://api.homemanager.com/ai
    description: Production server

security:
  - bearerAuth: []

paths:
  /insights/todos:
    post:
      tags:
        - Todo Insights
      summary: Get AI todo insights
      description: Get AI-powered insights and suggestions for todo management
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoInsightRequest'
      responses:
        '200':
          description: Insights generated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoInsightResponse'

  /insights/budget:
    post:
      tags:
        - Budget Insights
      summary: Get AI budget insights
      description: Get AI-powered financial insights and recommendations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BudgetInsightRequest'
      responses:
        '200':
          description: Insights generated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BudgetInsightResponse'

  /chat:
    post:
      tags:
        - AI Chat
      summary: Chat with AI assistant
      description: Interactive chat with AI assistant for home management advice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Chat response generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'

  /receipt/analyze:
    post:
      tags:
        - Receipt Analysis
      summary: Analyze receipt image
      description: Extract expense information from receipt images using AI
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                familyId:
                  type: string
                  format: uuid
      responses:
        '200':
          description: Receipt analyzed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReceiptAnalysisResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    TodoInsightRequest:
      type: object
      required:
        - familyId
      properties:
        familyId:
          type: string
          format: uuid
        context:
          type: string
          enum: [weekly_planning, optimization, delegation]
        timeframe:
          type: string
          enum: [week, month, quarter]
          default: week

    TodoInsightResponse:
      type: object
      properties:
        suggestions:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                enum: [new_todo, optimization, pattern]
              title:
                type: string
              description:
                type: string
              confidence:
                type: number
                format: float
              actionable:
                type: boolean
        patterns:
          type: array
          items:
            type: object
            properties:
              pattern:
                type: string
              frequency:
                type: string
              recommendation:
                type: string

    BudgetInsightRequest:
      type: object
      required:
        - familyId
      properties:
        familyId:
          type: string
          format: uuid
        analysisType:
          type: string
          enum: [spending_patterns, budget_optimization, savings_opportunities]
        timeframe:
          type: string
          enum: [month, quarter, year]
          default: month

    BudgetInsightResponse:
      type: object
      properties:
        insights:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                enum: [overspending, trend, opportunity]
              category:
                type: string
              message:
                type: string
              impact:
                type: number
                format: decimal
              confidence:
                type: number
                format: float
        recommendations:
          type: array
          items:
            type: object
            properties:
              action:
                type: string
              description:
                type: string
              expectedSavings:
                type: number
                format: decimal

    ChatRequest:
      type: object
      required:
        - familyId
        - message
      properties:
        familyId:
          type: string
          format: uuid
        message:
          type: string
        context:
          type: object
          description: Additional context for the conversation
        conversationId:
          type: string
          format: uuid
          description: ID to maintain conversation context

    ChatResponse:
      type: object
      properties:
        response:
          type: string
        conversationId:
          type: string
          format: uuid
        suggestions:
          type: array
          items:
            type: string
        confidence:
          type: number
          format: float

    ReceiptAnalysisResponse:
      type: object
      properties:
        merchantName:
          type: string
        totalAmount:
          type: number
          format: decimal
        date:
          type: string
          format: date
        items:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              amount:
                type: number
                format: decimal
              category:
                type: string
        suggestedCategory:
          type: string
        confidence:
          type: number
          format: float

    ErrorResponse:
      type: object
      required:
        - error
        - message
        - timestamp
      properties:
        error:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time